apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: andrewc-nginx
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.ibm.com/Andrew-Cleveland-CIC/andrewc-nginx.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true